# Default values for multiple-cronjobs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: busybox
  tag: 1.28
  pullPolicy: IfNotPresent 
name: mucsv-cron
namespace: cronjob
cronjobs: []