apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: {{ .Values.env }}
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: schedular
          - name: mucsv-schedular
            secret:
              secretName: mucsv-schedular
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: IfNotPresent
            args:
              - sh
              - -c
              - |
                sleep 2 
                "./bin/console {{ $.Values.command }}"
                sleep 30 
            volumeMounts:
            - name: data
              mountPath: /schedular
            - name: mucsv-schedular
              readOnly: true
              mountPath: /opt
          restartPolicy: OnFailure
