apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.crons.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: schedular
          - name: while
            secret:
              secretName: while
          containers:
          - name: {{ .Values.crons.name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - {{ .Values.crons.command }}
            volumeMounts:
            - name: data
              mountPath: /schedular
            - name: while
              readOnly: false
              mountPath: /opt
          restartPolicy: OnFailure
