apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: {{ .Values.env }}
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: schedular
          - name: while
            secret:
              secretName: while
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; /opt/while.sh
            volumeMounts:
            - name: data
              mountPath: /schedular
            - name: while
              readOnly: false
              mountPath: /opt
          restartPolicy: OnFailure
