apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: schedular
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi